---
- name: Include tasks for specific OS
  include: '{{ ansible_system }}/{{ ansible_os_family }}.yml'

- name: Straight to getenforce selinux status
  include: '{{ ansible_system }}/selinux.yml'

- name: Include firewall tasks
  include: '{{ ansible_system }}/firewall.yml'

- name: Include {{ item }} tasks
  include: '{{ ansible_system }}/{{ item | lower }}/{{ item | lower }}.yml'
  loop: '{{ os_linux_exporter_type }}'

- name: Registered with HashiCorp Consul
  include: '{{ ansible_system }}/{{ item | lower }}/register.yml'
  loop: '{{ os_linux_exporter_type }}'
  when:
    - consul_public_register | bool