---
- name: Disable unused module
  lineinfile:
    path: '/etc/modprobe.d/CIS.conf'
    create: 'yes'
    line: 'install {{ item }} /bin/true'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: "{{ vars['os_unload_module_' + ansible_os_family] }}"

- name: Black unused module
  lineinfile:
    path: '/etc/modprobe.d/blacklist.conf'
    create: 'yes'
    line: 'blacklist {{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop: "{{ vars['os_unload_module_' + ansible_os_family] }}"

- name: Unload unused file systems and network protocol modules
  modprobe:
    name: '{{ item }}'
    state: absent
  loop: "{{ vars['os_unload_module_' + ansible_os_family] }}"
