---
- name: Check windows OSSEC agent client.keys exists
  win_stat:
    path: '"C:\Program Files (x86)\ossec-agent\client.keys"'
  register: check_ossec_keys

- name: OSsec agent operation
  block:
    - name: Configuration the OSQuery
      include: '{{ ansible_system }}/osquery.yml'
    - name: Configuration the OSSEC agent
      include: '{{ ansible_system }}/configureation.yml'
    - name: Reload the OSSEC agent service
      win_service:
        name: 'wazuh'
        state: 'restarted'
        start_mode: 'auto'
      when: ossec_agent_auth_output.rc == 0
  when: not check_ossec_keys.stat.exists or check_ossec_keys.stat.size == 0
