---
- name: Check OSSec api are accessible from current host.
  win_uri:
    url: '{{ os_ossec_managers.api_proto }}://{{ os_ossec_agent_authd.address }}:{{ os_ossec_managers.api_port }}'
    method: 'GET'
    timeout: '5'
    validate_certs: 'no'
  environment:
    no_proxy: '{{ os_ossec_agent_authd.address }}'
  changed_when: false
  failed_when: false
  register: check_wazuh_api

- name: Create OSSec agent group.
  win_uri:
    url: '{{ os_ossec_managers.api_proto }}://{{ os_ossec_agent_authd.address }}:{{ os_ossec_managers.api_port }}/agents/groups/{{ group_names[0] | title | regex_replace("_", "-") }}?pretty'
    user: '{{ os_ossec_managers.api_user }}'
    password: '{{ os_ossec_managers.api_pass }}'
    method: 'PUT'
    status_code: '200'
    headers:
      X-Requested-By: '{{ os_ossec_agent_authd.address }}'
      cache-control: 'no-cache'
    validate_certs: 'no'
  environment:
    no_proxy: '{{ ansible_default_ipv4.address }}'
  when: check_wazuh_api.status_code == 401
  register: register_status
  until: register_status.status_code == 200
  retries: 3
  delay: 2
  no_log: true
  changed_when: false
  failed_when: false

- name: Get current OSSEC installed version
  win_command: '"C:\Program Files (x86)\ossec-agent\ossec-agent.exe" -h'
  register: ossec_agent_version
  failed_when: false
  changed_when: false

- name: Check OSSEC agent version installed
  set_fact: ossec_correct_version=true
  when:
    - os_ossec_agent_version.stdout is defined
    - os_ossec_version.split('-')[0] in ossec_agent_version.stdout

- name: Downloading windows OSSEC agent installer
  win_get_url:
    dest: C:\ossec-agent-installer.msi
    url: '{{ os_ossec_winagent_repo }}wazuh-agent-{{ os_ossec_version }}.msi'
  when: ossec_correct_version is not defined

- name: Install windows OSSEC agent
  win_package:
    path: C:\ossec-agent-installer.msi
  when: ossec_correct_version is not defined

- name: Delete downloaded OSSEC agent installer file
  win_file:
    path: 'C:\ossec-agent-installer.msi'
    state: 'absent'
  when: ossec_correct_version is not defined

- name: Register windows OSSEC agent
  win_command: '"C:\Program Files (x86)\ossec-agent\agent-auth.exe" -A {{ ansible_hostname | lower }} -m {{ os_ossec_agent_authd.address }} -p {{ os_ossec_agent_authd.port }} -P {{ os_ossec_agent_authd.authd_pass }} -G default,{{ group_names[-1] | upper | regex_replace("_", "-") }}'
  register: ossec_agent_auth_output
  changed_when: false
  failed_when: false
  no_log: true

- debug:
    msg: '{{ ossec_agent_auth_output.stderr_lines[-2] }}'
  when: ossec_agent_auth_output.rc != 0

- name: Windows OSSEC agent configuration file transfer
  win_template:
    src: 'ossec.conf.j2'
    dest: '"C:\Program Files (x86)\ossec-agent\ossec.conf"'
  when: ossec_agent_auth_output.rc == 0

- name: OSSEC agent internal options configuration file transfer
  win_template:
    src: 'local_internal_options.conf.j2'
    dest: '"C:\Program Files (x86)\ossec-agent\local_internal_options.conf"'
  when: ossec_agent_auth_output.rc == 0
