---
- name: Install chocolatey
  win_chocolatey:
    name: 'chocolatey'
    source: '{{ os_win_chocolatey_source }}'
    state: 'downgrade'
    version: '{{ os_win_chocolatey_version }}'
    timeout: '120'
  environment:
    no_proxy: '*'
  register: chocolatey_status
  until: chocolatey_status is succeeded
  retries: 10
  delay: 6
  changed_when: false
  failed_when: false

- name: Osquery software installation
  win_chocolatey:
    name: 'osquery'
    source: '{{ os_win_chocolatey_source }}'
    state: 'latest'
    timeout: '120'
  environment:
    no_proxy: '*'
  register: osquery_win_software_status
  until: osquery_win_software_status is succeeded
  retries: 10
  delay: 6
  changed_when: false
  failed_when: false

- name: Windows Osquery configuration file transfer
  win_copy:
    src: 'osquery.win.conf'
    dest: 'C:\Program Files\osquery\osquery.conf'
