---
- name: 'Miscellaneous specifications'
  win_regedit:
    path: '{{ item.path }}'
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: '{{ item.type }}'
  loop: '{{ os_win_misc_role }}'

- name: Disable scheduled task
  win_command: powershell.exe -
  args:
    stdin: 'Get-ScheduledTask -TaskName "{{ item }}" | Disable-ScheduledTask'
  loop: '{{ os_win_disable_task }}'
  when: os_win_disable_task is defined

- name: Disable AutomaticManaged pagefile and set C pagefile
  win_pagefile:
    drive: 'C'
    initial_size: '{{ os_win_pagefile_size | int }}'
    maximum_size: '{{ os_win_pagefile_size | int }}'
    remove_all: 'yes'
    automatic: 'no'
    state: 'present'
  when: os_win_pagefile_size is defined

- name: Set DNS Server addresses on all visible adapters
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: '{{ os_dns_server }}'
  when: os_dns_server is defined

#- name: Change Network Location to {{ win_network_location }}
#  win_command: powershell.exe -
#  args:
#    stdin: 'Set-NetConnectionProfile -Name "Network" -NetworkCategory {{ os_win_network_location }}'
