---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: OS software operation
  block:
    - name: Check if Linux software update already processed
      stat:
        path: '/etc/bootstrap_Software.Succeed'
      register: os_linux_soft_result
      when: ansible_system == 'Linux'
    - name: Include Linux software tasks
      include: 'Software/{{ ansible_system }}.yml'
      when:
        - ansible_system == 'Linux'
        - not os_linux_soft_result.stat.exists
    - name: Check if Windows software update already processed
      win_stat:
        path: 'c:\windows\bootstrap_Software.Succeed'
      register: os_win_soft_result
      when: ansible_system == 'Win32NT'
    - name: Include Windows software tasks
      include: 'Software/{{ ansible_system }}.yml'
      when:
        - ansible_system == 'Win32NT'
        - not os_win_soft_result.stat.exists
  when: os_software
  tags: software

- name: Include data disc tasks for specific OS
  include: 'Datadisc/{{ ansible_system }}.yml'
  when: os_datadisc
  tags: datadisc

- name: Include Prometheus Exporter tasks for specific OS
  include: 'Exporter/{{ ansible_system }}.yml'
  when: os_exporter
  tags: exporter

- name: OS Harden operation
  block:
    - name: Check if Linux Harden already processed
      stat:
        path: '/etc/bootstrap_Harden.Succeed'
      register: os_linux_harden_result
      when: ansible_system == 'Linux'
    - name: Include Linux Harden tasks
      include: 'Harden/{{ ansible_system }}.yml'
      when:
        - ansible_system == 'Linux'
        - not os_linux_harden_result.stat.exists
    - name: Check if Windows Harden already processed
      win_stat:
        path: 'c:\windows\bootstrap_Harden.Succeed'
      register: os_win_harden_result
      when: ansible_system == 'Win32NT'
    - name: Include Windows Harden tasks
      include: 'Harden/{{ ansible_system }}.yml'
      when:
        - ansible_system == 'Win32NT'
        - not os_win_harden_result.stat.exists
  when: os_harden
  tags: harden

- name: OS initialization configuration operation
  block:
    - name: Check if Linux initialization configuration already processed
      stat:
        path: '/etc/bootstrap_Config.Succeed'
      register: os_linux_config_result
      when: ansible_system == 'Linux'
    - name: Include Linux initialization configuration tasks
      include: 'Config/{{ ansible_system }}.yml'
      when:
        - ansible_system == 'Linux'
        - not os_linux_config_result.stat.exists
    - name: Check if Windows initialization configuration already processed
      win_stat:
        path: 'c:\windows\bootstrap_Config.Succeed'
      register: os_win_config_result
      when: ansible_system == 'Win32NT'
    - name: Include Windows initialization configuration tasks
      include: 'Config/{{ ansible_system }}.yml'
      when:
        - ansible_system == 'Win32NT'
        - not os_win_config_result.stat.exists
  when: os_config
  tags: config

- name: Include OSSec tasks for specific OS
  include: 'OSSec/{{ ansible_system }}.yml'
  when:
    - os_ossec
    - not ossec_is_install or ossec_is_install is not defined
  tags: ossec
