---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: OS software operation
  block:
    - name: Check if OS software update already processed
      stat:
        path: '{% if ansible_system == "Linux" %}/etc/{% else %}c:\windows\{% endif %}bootstrap_Software.Succeed'
      register: soft_result
    - name: Include OS software tasks
      include: 'Software/{{ ansible_system }}.yml'
      when: not soft_result.stat.exists
  when: os_software
  tags: software

- name: Include data disc tasks for specific OS
  include: 'Datadisc/{{ ansible_system }}.yml'
  when: os_datadisc
  tags: datadisc

- name: OS Harden operation
  block:
    - name: Check if OS harden already processed
      stat:
        path: '{% if ansible_system == "Linux" %}/etc/{% else %}c:\windows\{% endif %}bootstrap_Harden.Succeed'
      register: harden_result
    - name: Include OS harden tasks
      include: 'Harden/{{ ansible_system }}.yml'
      when: not harden_result.stat.exists
  when: os_harden
  tags: harden

- name: OS initialization configuration operation
  block:
    - name: Check if OS initialization configuration already processed
      stat:
        path: '{% if ansible_system == "Linux" %}/etc/{% else %}c:\windows\{% endif %}bootstrap_Config.Succeed'
      register: config_result
    - name: Include OS initialization configuration tasks
      include: 'Config/{{ ansible_system }}.yml'
      when: not config_result.stat.exists
  when: os_config
  tags: config
