---
- include: audit.yml

- include: password.yml

- include: firewall.yml

- name: Ensure harden status file
  win_copy:
    src: 'bootstrap_Harden.Succeed'
    dest: 'c:\windows\bootstrap_Harden.Succeed'