---
- include: '{{ ansible_system }}/{{ ansible_os_family }}/Resource.yml'

- include: '{{ ansible_system }}/{{ ansible_os_family }}/{{ ansible_distribution_major_version }}/Service.yml'

- include: '{{ ansible_system }}/{{ ansible_os_family }}/{{ ansible_distribution_major_version }}/NTP.yml'
  when: os_time_server is defined

- include: '{{ ansible_system }}/{{ ansible_os_family }}/{{ ansible_distribution_major_version }}/Rsyslog.yml'
  when: os_syslog | bool

- include: '{{ ansible_system }}/Environment.yml'

- include: '{{ ansible_system }}/Timezone.yml'

- include: '{{ ansible_system }}/{{ ansible_os_family }}/DNS.yml'
  when: os_dns_server is defined

- include: '{{ ansible_system }}/{{ ansible_os_family }}/{{ ansible_distribution_major_version }}/Grub.yml'

- name: Ensure configuraion status file
  copy:
    src: 'bootstrap_Config.Succeed'
    dest: '/etc/bootstrap_Config.Succeed'
    owner: 'root'
    group: 'root'
    mode: '0644'
