---
- include: '{{ ansible_system }}/nxlog.yml'
  when: gelf_syslog

- include: '{{ ansible_system }}/ipv6.yml'

- include: '{{ ansible_system }}/rss.yml'

- include: '{{ ansible_system }}/misc.yml'

- include: '{{ ansible_system }}/timezone.yml'

- include: '{{ ansible_system }}/region.yml'

- name: Ensure configuraion status file
  win_copy:
    src: 'bootstrap_Config.Succeed'
    dest: 'c:\windows\bootstrap_Config.Succeed'

- win_reboot:
    reboot_timeout: '3600'
  when: result.restart_required
