---
- name: Add OSQuery YUM repositories
  yum_repository:
    name: '{{ os_osquery_repo_name }}'
    description: '{{ os_osquery_repo_name }} YUM repo'
    file: '{{ os_osquery_repo_name }}'
    baseurl: '{{ os_osquery_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Add OSSEC YUM repositories
  yum_repository:
    name: '{{ os_ossec_repo_name }}'
    description: '{{ os_ossec_repo_name }} YUM repo'
    file: '{{ os_ossec_repo_name }}'
    baseurl: '{{ os_ossec_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the OSSEC agent dependents packages
  yum:
    name: '{{ ossec_agent_dependent_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2

- name: Install the OSSEC agent packages
  yum:
    name: '{{ os_ossec_agent_packages }}'
    state: 'present'
    enablerepo: '{{ ossec_repo_name }}'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2
