---
- name: Add PowerBroker YUM repositories.
  yum_repository:
    name: '{{ os_pbis_repo_name }}'
    description: '{{ os_pbis_repo_name }}'
    file: '{{ os_pbis_repo_name }}'
    baseurl: '{{ os_pbis_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the PowerBroker packages.
  package: 
    name: '{{ os_pbis_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2
