---
- name: Generate RHEL7 new grub config
  shell: grub2-mkconfig -o /etc/grub2.cfg

- name: Enable OSQuery service
  systemd:
    name: 'osqueryd.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  listen: Ensure OSQuery service is enabled

- name: Enable OSSEC agent service
  systemd:
    name: 'wazuh-agent.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  listen: Ensure OSSEC agent service is enabled
