---
- name: Disable unused file systems and network protocols
  lineinfile:
    path: '/etc/modprobe.d/CIS.conf'
    create: 'yes'
    line: 'install {{ item }} /bin/true'
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ vars['unload_module_' + ansible_os_family] }}"
  register: result

- name: Unload unused file systems and network protocol modules
  modprobe:
    name: '{{ item }}'
    state: absent
  with_items:
    - "{{ vars['unload_module_' + ansible_os_family] }}"
