---
- name: Gathering service facts
  service_facts:
  register: services_state

- name: Resolver configuration file transfer
  template:
    src: 'resolv.conf.j2'
    dest: '/etc/resolv.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: services_state.ansible_facts.services["NetworkManager.service"] is not defined or services_state.ansible_facts.services["NetworkManager.service"].state != 'running'
