---
- name: Configure runtime kernel parameters
  template:
    src: '10-sysctl.conf.j2'
    dest: '/etc/sysctl.d/10-sysctl.conf'
    owner: root
    group: root
    mode: 0644
  register: result

- name: Loading sysctl settings
  shell: sysctl -p
  when: 
    - result.changed

- name: Set nofile limits
  lineinfile:
    dest: /etc/security/limits.conf
    state: present
    line: '{{ item }}'
  with_items:
    - '* soft nofile 16384'
    - '* hard nofile 16384'

- name: Set nproc limits
  lineinfile: 
    dest: /etc/security/limits.d/90-nproc.conf
    insertafter: EOF
    state: present
    create: yes
    mode: 0644
    line: '{{ item }}'
  with_items:
    - '* soft nproc 16384'
    - '* hard nproc 16384'
