---
- name: 'Allow firewall operation'
  block:
    - name: Allow node exporter service port
      lineinfile:
        dest: '/etc/sysconfig/iptables'
        regexp: '^-A INPUT -p tcp -m tcp --dport {{ item.port }} -j ACCEPT$'
        line: '-A INPUT -p tcp -m tcp --dport {{ item.port }} -j ACCEPT'
        insertafter: '^:OUTPUT ACCEPT \[\d*:\d*\]$'
      loop: '{{ os_linux_exporter_type }}'
    - name: Reload the node exporter service firewalld
      service:
        name: 'iptables'
        state: 'reloaded'
  when: 
    - ansible_distribution_major_version|int == 6

- name: Gathering service facts
  service_facts:
  register: services_state

- name: 'Allow firewall operation'
  firewalld:
    port: '{{ item.port }}/tcp'
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop: '{{ os_linux_exporter_type }}'
  when: 
    - ansible_distribution_major_version|int > 6
    - services_state.ansible_facts.services["firewalld.service"] is defined
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'
