---
- name: Node exporter configure file transfer
  template:
    src: 'node_exporter.j2'
    dest: '/etc/default/node_exporter'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: soft_config

- name: Reloading the node exporter service
  service:
    name: 'node_exporter'
    enabled: 'yes'
    state: 'restarted'
  when:
    - ansible_distribution_major_version|int == 6
    - soft_config is changed

- name: Reloading the node exporter service
  systemd:
    name: 'node_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  when:
    - ansible_distribution_major_version|int > 6
    - soft_config is changed

- name: Node exporter collector scripts transfer
  template:
    src: 'scripts/{{ ansible_system }}/{{ item }}.j2'
    dest: '/usr/local/bin/{{ item }}.sh'
    owner: 'root'
    group: 'root'
    mode: '0755'
  loop: '{{ os_node_exporter_collector_textfile_scritps }}'

- name: Creating Node exporter collector textfile folder
  file:
    dest: '{{ os_node_exporter_collector_textfile_directory }}'
    state: 'directory'
    mode: '0755'

- name: Check information collection exists
  stat:
    path: '/var/lib/prometheus/{{ item }}.prom'
  loop: '{{ os_node_exporter_collector_textfile_scritps }}'
  register: check_prom_files

- name: Execute Node information collection
  shell: '/usr/local/bin/{{ item.prom }}.sh > {{ os_node_exporter_collector_textfile_directory }}/{{ item.prom }}.prom'
  loop: "{{ check_prom_files.results | json_query('[*].{prom:item,exists:stat.exists,size:stat.size}') }}"
  when: not item.exists or item.size == 0

- name: Create a scheduled task to node info collector 
  cron:
    user: 'root'
    name: 'text collector {{ item }}'
    special_time: 'daily'
    job: '/usr/local/bin/{{ item }}.sh > {{ os_node_exporter_collector_textfile_directory }}/{{ item }}.prom'
  loop: '{{ os_node_exporter_collector_textfile_scritps }}'
