---
- name: 'Add {{ item }} YUM repositories'
  yum_repository:
    name: '{{ vars[item + "_repo_name"] }}'
    description: '{{ vars[item + "_repo_name"] }} YUM repository'
    file: '{{ vars[item + "_repo_name"] }}'
    baseurl: '{{ vars[item + "_repo_url"] }}'
    gpgcheck: 'no'
    timeout: '60'
  loop: '{{ os_linux_exporter_type | lower }}'

- name: 'Install the {{ item }}'
  yum:
    name: '{{ vars[item + "_software"] }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: soft_updated
  until: soft_updated is succeeded
  retries: 3
  delay: 5
  loop: '{{ os_linux_exporter_type | lower }}'