---
- name: 'Add exporter YUM repositories'
  yum_repository:
    name: '{{ vars[item.name + "_repo_name"] }}'
    description: '{{ vars[item.name + "_repo_name"] }} YUM repository'
    file: '{{ vars[item.name + "_repo_name"] }}'
    baseurl: '{{ vars[item.name + "_repo_url"] }}'
    gpgcheck: 'no'
    timeout: '60'
  loop: '{{ os_linux_exporter_type }}'

- name: 'Install the exporter'
  yum:
    name: '{{ vars[item.name + "_software"] }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: soft_updated
  until: soft_updated is succeeded
  retries: 3
  delay: 5
  loop: '{{ os_linux_exporter_type }}'
