---
- name: Add exporter YUM repositories
  yum_repository:
    name: '{{ vars["os_" + item.name + "_repo_name"] }}'
    description: '{{ vars["os_" + item.name + "_repo_name"] }} YUM repository'
    file: '{{ vars["os_" + item.name + "_repo_name"] }}'
    baseurl: '{{ vars["os_" + item.name + "_repo_url"] }}'
    gpgcheck: 'no'
    timeout: '60'
  loop: '{{ os_linux_exporter_type }}'

- name: Install the exporter
  yum:
    name: '{{ vars["os_" + item.name + "_software"] }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: soft_updated
  until: soft_updated is succeeded
  retries: 5
  delay: 2
  loop: '{{ os_linux_exporter_type }}'
