---
- name: Get disk facts
  raw: GET-WMIOBJECT win32_logicaldisk -fi "drivetype=3" | Select-Object -ExpandProperty DeviceID
  register: fs_audit_path

- name: Configure event log maxsize limitation
  win_regedit:
    path: 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\{{ item }}'
    name: 'MaxSize'
    data: '{{ os_win_event_log_MaxSize }}'
    type: dword
  loop: '{{ os_win_event_log }}'

- name: Configure local security policy
  win_audit_policy_system:
    category: '{{ item }}'
    audit_type: success, failure
  loop: '{{ os_win_gpo_audit_policy }}'

- name: Configure filesystem audit rule 
  win_audit_rule:
    path: '{{ item }}'
    user: '{{ os_win_fs_audit_user }}'
    rights: '{{ os_win_fs_audit_rule | list | join(",") }}'
    audit_flags: 'success,failure'
    inheritance_flags: 'ContainerInherit,ObjectInherit'
  loop: '{{ fs_audit_path.stdout_lines }}'
