---
- name: Update Grub default config
  replace:
    dest: '/etc/grub.conf'
    regexp: 'quiet'
    replace: "{{ os_linux_grub_add_args | join(' ') }}"
  register: grub
  when: os_linux_grub_add_args is defined
