---
- name: Add rsyslog YUM repositories
  yum_repository:
    name: '{{ rsyslog_repo_name }}'
    description: '{{ rsyslog_repo_name }} RPM repository for Enterprise Linux'
    file: '{{ rsyslog_repo_name }}'
    baseurl: '{{ rsyslog_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Upgrade the rsyslog
  yum:
    name: '{{ item }}'
    state: 'latest'
  loop: '{{ rsyslog_packages }}'
  register: soft_update
  until: soft_update is succeeded
  retries: 3
  delay: 5

- name: Remote rsyslog Configuration
  template:
    src: 'rsyslog.conf.j2'
    dest: '/etc/rsyslog.conf'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: conf_update

- name: Reload rsyslog service
  service:
    name: 'rsyslog'
    enabled: 'yes'
    state: 'restarted'
  async: 1
  poll: 0
  when:
    - soft_update is changed
    - conf_update is changed

- name: Local syslog logrotate parameters
  template:
    src: 'logrotate.conf.j2'
    dest: '/etc/logrotate.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
