---
- name: Add rsyslog YUM repositories
  yum_repository:
    name: '{{ rsyslog_repo_name }}'
    description: '{{ rsyslog_repo_name }} RPM repository for Enterprise Linux'
    file: '{{ rsyslog_repo_name }}'
    baseurl: '{{ rsyslog_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Upgrade the rsyslog
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ rsyslog_packages }}'
  register: soft_update

- name: Remote rsyslog Configuration
  lineinfile:
    dest: /etc/rsyslog.conf
    state: present
    line: '{{ item }}'
  with_items:
    - '$PreserveFQDN on'
    - 'template(name="gelf" type="list") {'
    - '  constant(value="{\"version\":\"1.1\",")'
    - '  constant(value="\"host\":\"") property(name="hostname" caseConversion="upper")'
    - '  constant(value="\",\"short_message\":\"") property(name="msg" format="json")'
    - '  constant(value="\",\"timestamp\":") property(name="timereported" dateformat="unixtimestamp")'
    - '  constant(value=",\"level\":\"") property(name="syslogseverity")'
    - '  constant(value="\",\"facility\":\"") property(name="syslogfacility")'
    - '  constant(value="\",\"appname\":\"") property(name="APP-NAME")'
    - '  constant(value="\",\"procid\":\"") property(name="PROCID")'
    - '  constant(value="\"}")'
    - '}'
    - 'action(type="omfwd" target="{{ gelf_syslog_server | list | random }}" port="{{ gelf_syslog_port }}" protocol="{{ gelf_syslog_protocol }}" template="gelf")'
  register: conf_update

- name: Reload rsyslog service
  service:
    name: rsyslog
    enabled: yes
    state: restarted
  async: 1
  poll: 0
  when:
    - soft_update.changed
    - conf_update.changed

- name: Local syslog logrotate parameters
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: 0644
