---
- name: Ensure file permissions are configured.
  file:
    path: '{{ item.file }}'
    owner: 'root'
    group: 'root'
    mode: '{{ item.mode }}'
  loop: '{{ os_linux_protected_file}}'
  changed_when: false
  failed_when: false