---
- name: Update Grub default config
  replace:
    dest: '/etc/default/grub'
    regexp: "net.ifnames=0"
    replace: "net.ifnames=0 {{ os_linux_grub_add_args | join(' ') }}"
  notify: Generate RHEL7 new grub config
  register: grub
  when: os_linux_grub_add_args is defined

- name: Force the handler to run immediately
  meta: flush_handlers
