---
- name: NTP system configuration
  template:
    src: 'chrony.conf.j2'
    dest: '/etc/chrony.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: os_ntp_update

- name: Reload NTP service
  systemd:
    name: 'chronyd.service'
    enabled: 'yes'
    state: 'restarted'
  async: 1
  poll: 0
  when: os_ntp_update is changed
