---
- name: Remote rsyslog Configuration
  template:
    src: 'rsyslog.conf.j2'
    dest: '/etc/rsyslog.conf'
    backup: 'yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: conf_update

- name: Ignore flooded logs with systemd messages
  copy:
    src: 'ignore-systemd-session-slice.conf'
    dest: '/etc/rsyslog.d/ignore-systemd-session-slice.conf'

- name: Reload rsyslog service
  systemd:
    name: 'rsyslog.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  async: 1
  poll: 0
  when:
    - conf_update is changed

- name: Local syslog logrotate parameters
  template:
    src: 'logrotate.conf.j2'
    dest: '/etc/logrotate.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
