---
- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: Ensure update status file
  copy:
    src: 'bootstrap_Software.Succeed'
    dest: '/etc/bootstrap_Software.Succeed'
    owner: root
    group: root
    mode: 0644
