---
- name: 'Add EPEL YUM repositories'
  yum_repository:
    name: '{{ epel_repo_name }}'
    description: '{{ epel_repo_name }} YUM repo'
    file: '{{ epel_repo_name }}'
    baseurl: '{{ epel_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: 'Configure YUM proxy'
  lineinfile:
    dest: '/etc/yum.conf'
    line: 'proxy={{ proxy_server }}'
  when: proxy_server is defined

- name: 'Install the base packages'
  yum:
    name: '{{ ",".join(vars["base_packages_" + ansible_os_family + "_" + ansible_distribution_major_version]) }}'
    state: 'present'
    update_cache: 'yes'

- name: 'Remove the useless packages'
  yum:
    name: '{{ ",".join(vars["remove_packages_" + ansible_os_family + "_" + ansible_distribution_major_version]) }}'
    state: 'absent'

- name: 'Update all packages'
  yum:
    name: '*'
    state: 'latest'
