---
- name: 'Installs roles or features'
  win_feature:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - '{{ os_win_roles }}'
  ignore_errors: yes

- name: Install chocolatey
  win_chocolatey:
    name: 'chocolatey'
    state: 'downgrade'
    version: '{{ win_chocolatey_version }}'
    proxy_url: '{{ os_proxy_server | default(omit,true) }}'
  register: chocolatey_status
  until: chocolatey_status is succeeded
  retries: 10
  delay: 6
  changed_when: false
  failed_when: false

- name: 'Third party software installation'
  win_chocolatey:
    name: '{{ item }}'
    state: 'latest'
    timeout: '60'
    proxy_url: '{{ os_proxy_server | default(omit,true) }}'
  with_items:
    - '{{ os_win_software }}'
  register: os_win_software_status
  until: os_win_software_status is succeeded
  retries: 10
  delay: 6
  changed_when: false
  failed_when: false

- name: Install security updates
  win_updates:
    category_names: '{{ os_win_update_category }}'
  ignore_errors: yes

- name: Ensure update status file
  win_copy:
    src: 'bootstrap_Software.Succeed'
    dest: 'c:\windows\bootstrap_Software.Succeed'
