---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- include: '{{ ansible_os_family }}/Resource.yml'
  tags: resource

- include: '{{ ansible_os_family }}/{{ ansible_distribution_major_version }}/Service.yml'
  tags: service

- include: '{{ ansible_os_family }}/Security.yml'
  tags: security

- include: '{{ ansible_os_family }}/Modules.yml'
  tags: module

- include: '{{ ansible_os_family }}/{{ ansible_distribution_major_version }}/Rsyslog.yml'
  when: syslog_remote
  tags: rsyslog

- include: '{{ ansible_os_family }}/Audit.yml'
  tags: audit

- include: '{{ ansible_os_family }}/User.yml'
  tags: user

- include: '{{ ansible_os_family }}/Filesystem.yml'
  tags: filesystem

- include: 'Environment.yml'
  tags: environment

- include: 'Selinux.yml'
  tags: selinux

- include: 'Password.yml'
  tags: password

- include: 'Timezone.yml'
  tags: timezone

- include: '{{ ansible_os_family }}/{{ ansible_distribution_major_version }}/Grub.yml'
  tags: grub

- name: Ensure harden status file
  copy:
    src: 'Harden.Succeed'
    dest: '/etc/Harden.Succeed'
    owner: root
    group: root
    mode: 0644

- name: Restart the host
  shell: sleep 2 && /sbin/shutdown -r now "Ansible system required"
  async: 1
  poll: 0
  ignore_errors: true
  when: grub.changed
